//
//  CCMContact+CoreDataProperties.swift
//  DropBit
//
//  Created by Ben Winters on 2/20/19.
//  Copyright © 2019 Coin Ninja, LLC. All rights reserved.
//
//

import Foundation
import CoreData

extension CCMContact {

  @nonobjc public class func fetchRequest() -> NSFetchRequest<CCMContact> {
    return NSFetchRequest<CCMContact>(entityName: "CCMContact")
  }

  /// Identifier of Apple's CNContact, unique only to this device
  @NSManaged public var cnContactIdentifier: String

  /// generated by CNContactFormatter
  @NSManaged public var displayName: String

  @NSManaged public var givenName: String?
  @NSManaged public var familyName: String?

  @NSManaged public var cachedPhoneNumbers: Set<CCMPhoneNumber>

}
