# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone SE",
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone 11",
  "iPhone 11 Pro Max"
])

languages([
  "en-US",
])

# The name of the scheme which contains the UI Tests
scheme("DropBitSnapshot")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

reinstall_app(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
