
// Objective-C API for talking to the following Go packages
//
//	git.coinninja.net/engineering/cnlib
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Cnlib_FRAMEWORK_H__
#define __Cnlib_FRAMEWORK_H__

#include "CNBCnlib.objc.h"
#include "Universe.objc.h"

#endif
